export const brandPrimary = '#FCA033'
export const brandSecondary = '#F47A40'
export const brandDark = '#5A5B5D'
export const brandLight = '#FFFFFF'
export const white = '#FFFFFF'
export const paleGray = '#F4F4F4'
export const palerGray = '#FAFAFA'
export const lightestGray = '#DEDEDF'
export const lighterGray = '#BDBEBF'
export const lightGray = '#9D9D9E'
export const gray = '#7C7D7E'
export const darkGray = '#6C6D6E'
export const darkerGray = '#5A5B5D'
export const darkestGray = '#101010'
export const black = '#000000'
export const brandBlue = '#1b4778'
export const brandBlueSecondary = '#076bda'
export const darkBlue = '#333d4c'
export const darkerBlue = '#232934'
export const darkestBlue = '#181c23'
export const buttonUnderlay = '#181c23'
export const bodyFontColor = '#5A5B5D'
export const success = '#3BB249' // green
export const alert = '#FFDA49' // orange
export const warning = '#E52D2D' // red
export const error = '#E52D2D' // red
export const info = '#FCA033' // BrandPrimary